name: 'Coding Challenges'
description: 'Verify & store a challenge result'
inputs:
  repo-token:
    description: 'The token for this job'
    required: true
    default: 'no-token'
  pr-number:
    description: 'The PR number'
    required: true
    default: '0'
  pr-author:
    description: 'The PR author'
    required: true
    default: '?'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}