name: 'Coding Challenges'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'The token for this job'
    required: true
    default: 'no-token'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}